version: '3.8'

services:

  main:
    build: ./
    command: ./film-library
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432/tcp