port: "8080"

db:
#  host:     "localhost"
  host:     "db"
  port:     "5432"
  username: "postgres"
  dbname:   "postgres"
#  dbname: "filmLibrary"
  sslmode:  "disable"
  migration_url: "file://migrations"